{% set name = "ansys_tools_protoc_helper" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3af6b5d78e1edd389890b54fed4f3fd3e0862463366a2e3bc4e2b2dffbb6158f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7,<3.11
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.7,<3.11
    - setuptools >=42.0
    - grpcio-tools ==1.44.0
    - protobuf ==3.19.3
    - mypy-protobuf ==3.1.0
    - importlib-resources >=1.3

test:
  imports:
    - ansys.tools.protoc_helper
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/ansys-tools-protoc-helper/
  summary: A utility for compiling '.proto' files to Python source.
  dev_url: https://github.com/ansys/ansys-tools-protoc-helper
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - SMoraisAnsys
    - MaxJPRey
    - jorgepiloto
    - RobPasMue
